config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'worlds#index'

  resources :worlds do
    resources :characters
  end

  # Good use of nested resources
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :world
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/world.rb
class World < ApplicationRecord
  has_many :characters, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  # To write a little less code, you could also use
  # before_action :authenticate_user!, except: [:index, :show]


  def index
    @characters = Character.all
  end

  def show
    @world = World.find(params[:world_id])
    @character = Character.find(params[:id])
  end

  def new
    @world = World.find(params[:world_id])
    @character = Character.new
  end

  def create
    @world = World.find(params[:world_id])
    @character = @world.characters.create(character_params)

    redirect_to world_character_path(@world, @character)
  end

  def edit
    @world = World.find(params[:world_id])
    @character = Character.find(params[:id])
  end

  def update
    @world = World.find(params[:world_id])
    @character = Character.find(params[:id])
    @character.update(character_params)

    redirect_to world_character_path(@world, @character)
  end

  def destroy
    @world = World.find(params[:world_id])
    @character = Character.find(params[:id])
    @character.destroy

    redirect_to world_path(@world)
  end

  private
    def character_params
      params.require(:character).permit(:name, :img_url, :origin ,:description)
    end
end

app/controllers/worlds_controller.rb
class WorldsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @worlds = World.all
  end

  def show
    @world = World.find(params[:id])
  end

  def new
    @world = World.new
  end

  def create
    @world = World.create(world_params)

    redirect_to world_path(@world)
  end

  def edit
    @world = World.find(params[:id])
  end

  def update
    @world = World.find(params[:id])
    @world.update(world_params)

    redirect_to world_path(@world)
  end

  def destroy
    @world = World.find(params[:id])
    @world.destroy

    redirect_to worlds_path
  end

  private
    def world_params
      params.require(:world).permit(:name, :img_url, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/characters/edit.html.erb
<section class="wrapper">
  <header class="main-header">
    <h2>Edit Character /
      <%= link_to @character.name, world_character_path %></h2>
  </header>
  <main class="form-content">
    <%= simple_form_for [@world, @character], :html => {:class => "pure-form pure-form-stacked"} do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="form-group">
      <%= f.label :img_url %>
      <%= f.text_field :img_url %>
    </div>

    <div class="form-group">
      <%= f.label :origin %>
      <%= f.text_field :origin %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>

    <div class="form-submit">
      <%= f.submit %>
    </div>

    <% end %>

    <%= simple_form_for [@world, @character], method: :delete do |f| %>
    <div class="form-delete">
      <%= f.submit "Delete" %>
    </div>
    <% end %>

  </main>
</section>

app/views/characters/index.html.erb
<%# Any view that is not being used (or code / file in general), go ahead and delete from
the application before pushing to production %>

app/views/characters/new.html.erb
<section class="wrapper">
  <header class="main-header">
    <h2>New Character /
      <%= link_to @world.name, world_path(@world) %></h2>
  </header>

  <main class="form-content">
    <%= simple_form_for [@world, @character], :html => {:class => "pure-form pure-form-stacked"} do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="form-group">
      <%= f.label :img_url %>
      <%= f.text_field :img_url %>
    </div>

    <div class="form-group">
      <%= f.label :origin %>
      <%= f.text_field :origin %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>

    <div class="form-submit">
      <%= f.submit %>
    </div>
    <% end %>
  </main>
</section>

app/views/characters/show.html.erb
<section class="wrapper">
  <header class="main-header">
    <h2><%= @character.name %></h2>
    <p><%= @character.origin %> / <%= link_to @character.world.name, world_path(@world) %></p>
  </header>

  <main class="content">
    <div class="column-left">
      <div class="character">
        <%= image_tag @character.img_url %>
      </div>
    </div>

    <div class="column-right">
      <p class="item-text">
        <%= @character.description %>
      </p>

      <div class="links">
        <%# I'm surprised the link below works and would recommend that you still
        give it inputs representing the world / character in question %>
        <%= link_to 'Edit', edit_world_character_path(@world, @character)%>
      </div>
    </div>

  </main>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kingdom Hearts Universe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'https://unpkg.com/purecss@0.6.2/build/pure-min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://cdnjs.cloudflare.com/ajax/libs/normalize/6.0.0/normalize.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Libre+Baskerville:400,400i" rel="stylesheet">
    <%# nice job bringing in css / font libraries and using a css normalize %>

  </head>

  <body>
    <div class="top-info">
      <% if user_signed_in? == true %>
      <div class="user-action"><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></div>
      <div class="user-info">Welcome,
        <%= current_user.email %></div>
    <% else %>
      <div class="user-action"><%= link_to 'Login', new_user_session_path %>
        |
        <%= link_to 'Sign Up', new_user_registration_path %></div>
      <% end %>
    </div>

    <section class="title">
      <a href="<%= worlds_path %>"><%= image_tag 'crown.png' %></a>
      <h1>Kingdom Hearts</h1>
      <p>Universe</p>
    </section>

    <div class="wrapper">
      <div class="flash">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    </div>

    <%= yield %>

    <footer class="footer-text">
      <p>Design by
        <%= link_to 'Halimatu Bakarr', 'http://halimatubakarr.com' %>. Built with Rails.</p>
    </footer>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/worlds/edit.html.erb
<section class="wrapper">
  <header class="main-header">
    <h2>Edit World / <%= link_to @world.name, world_path(@world) %></h2>
  </header>

  <main class="form-content">
    <%= simple_form_for @world, :html => {:class => "pure-form pure-form-stacked"} do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div class="form-group">
        <%= f.label :img_url %>
        <%= f.text_field :img_url %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description %>
      </div>

      <div class="form-submit">
        <%= f.submit %>
      </div>

    <% end %>

    <%= simple_form_for @world, method: :delete do |f| %>
      <div class="form-delete">
        <%= f.submit "Delete"%>
      </div>
    <% end %>

  </main>
</section>

app/views/worlds/index.html.erb
<section class="wrapper">
  <div class="world-list">
    <div class="world-wrapper">
      <% @worlds.each do |world| %>
      <div class="world" style="background: url(<%= world.img_url %>); background-size: 60%; background-position: center 20%; background-repeat: no-repeat;">
        <a href="<%= world_path(world) %>">
          <h2><%= world.name %></h2>
        </a>
        <%# While templating in the url for href works just fine, you could also use %>
        <% link_to world_path(@world) do %>
          <h2><%= world.name %></h2>
        <% end %>
      </div>
      <% end %>
    </div>

    <div class="links">
      <%= link_to 'Add New', new_world_path %>
    </div>

  </div>
</section>

app/views/worlds/new.html.erb
<section class="wrapper">
  <header class="main-header">
    <h2>New World</h2>
    <p><%= link_to 'Back', worlds_path %></p>
  </header>

  <main class="form-content">
    <%= simple_form_for @world, :html => {:class => "pure-form pure-form-stacked"} do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="form-group">
      <%= f.label :img_url %>
      <%= f.text_field :img_url %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>

    <div class="form-submit">
      <%= f.submit %>
    </div>
    <% end %>

  </main>
</section>

app/views/worlds/show.html.erb
<section class="wrapper">
  <header class="main-header">
    <h2><%= @world.name %></h2>
    <p><%= link_to 'Back', worlds_path %></p>
  </header>

  <main class="content">
    <div class="column-left">
      <div class="world-single">
        <%= image_tag @world.img_url %>
      </div>
    </div>

    <div class="column-right">
      <p class="item-text">
        <%= @world.description %>
      </p>

      <div class="links">
        <%= link_to 'Edit', edit_world_path %>
      </div>

      <div class="character-section">
        <h4>Characters</h4>
        <% @world.characters.each do |character| %>
        <p class="character-name">
          <%= link_to character.name, world_character_path(@world, character)  %>
        </p>
        <% end %>
        <div class="new-character">
          <%= link_to '+ Add New', new_world_character_path(@world, @character) %>
        </div>
      </div>

    </div>
  </main>

</section>